Parameters:
  CimaBucket:
    Type: String
    Description: The name of the bucket that contains the ManagementAccountStackset YAML files
  PrincipalOrgID:
    Type: String
    Description: The AWS organization ID of the principal that is allowed to put events on the custom Cima event bus.
  QuickSightUser:
    Type: String
    Description: The QuickSight User that is allowed configure and manage the QS dashboard. e.g. Admin/sample-isgr, quicksightuser etc.
  QuicksightServiceRole:
    Type: String
    Description: The Quicksight Service role attached to QS, Default is aws-quicksight-service-role-v0

Resources:
  CimaCentralAccSetup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CimaBucket}.s3.amazonaws.com/CimaTemplates/Cima-CentralAccSetup.yaml
      Parameters:
        POrgID: !Ref PrincipalOrgID
        
  CimaCaseAccSetup:
     Type: AWS::CloudFormation::Stack
     Properties:
       TemplateURL: !Sub https://${CimaBucket}.s3.amazonaws.com/CimaTemplates/Cima-LinkAccSetup.yaml
       Parameters:
        CimaBusArn: !GetAtt CimaCentralAccSetup.Outputs.CimaBusArn

  CimaConnectorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CimaBucket}.s3.amazonaws.com/CimaTemplates/Cima-Connector-Setup.yaml
      Parameters:
        CimaDDBTableArn: !GetAtt  CimaCentralAccSetup.Outputs.CimaDDBTableArn
        CimaBucket: !Ref CimaBucket
        
  CimaQSDatasetSetup:
    Type: AWS::CloudFormation::Stack
    DependsOn: CimaCaseAccSetup
    Properties:
      TemplateURL: !Sub https://${CimaBucket}.s3.amazonaws.com/CimaTemplates/Cima-QSDatasetSetup.yaml
      Parameters:
        CimaDataCatalog: !GetAtt  CimaConnectorStack.Outputs.CimaDataCatalog
        QuickSightUser: !Ref QuickSightUser
        CimaDDBTableName: !GetAtt  CimaCentralAccSetup.Outputs.CimaDDBTableName
        CimaDDBConnectorARN: !GetAtt CimaConnectorStack.Outputs.CimaDDBConnectorARN
        QuicksightServiceRole: !Ref QuicksightServiceRole
        CimaBucket: !Ref CimaBucket
 
  CimaQSAnalysisSetup:
    Type: AWS::CloudFormation::Stack
    DependsOn: CimaCaseAccSetup
    Properties:
      TemplateURL: !Sub https://${CimaBucket}.s3.amazonaws.com/CimaTemplates/Cima-QSAnalysisSetup.yaml
      Parameters:
        CimaQSDataSetArn: !GetAtt  CimaQSDatasetSetup.Outputs.CimaQSDataSetArn
        QuickSightUser: !Ref QuickSightUser
